sudo: false

language:
  - python

python:
  - 2.7
  - 3.4
  - 3.5

branches:
  only:
  - master
  - develop
  
install:
  - pip install pytest pytest-cov python-coveralls

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then py.test -vv main.py --cov main;
    else py.test -vv main.py;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then coveralls;
    fi

notifications:
  email: false