sudo: false

language:
  - python

python:
  - 3.5

install:
  - pip install pytest pytest-cov python-coveralls

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then py.test -vv main.py --cov main;
    else py.test -vv main.py;
    fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then coveralls;
    fi

deploy:
  # 部署到GitHub Release。
  # 除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
  provider: releases
  # Github oauth token
  api_key: "$GH_TOKEN"
  # 部署文件路径；对于Android就部署生成的 apk 文件
  file:
    - main.py
  # 避免 Travis CI在部署之前清空生成的APK文件
  skip_cleanup: true
  on:
    # tags设置为true表示只有在有tag的情况下才部署
    tags: true
    all_branches: true
