sudo: false

language:
  - python

python:
  - 3.5

branches:
  only:
  - master
  - develop
  
install:
  - pip install pytest pytest-cov python-coveralls

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then py.test -vv main.py --cov main;
    else py.test -vv main.py;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then coveralls;
    fi

deploy:
    # This is the deploy target for the native build (Linux and macOS)
    # which generates the source tarball.
    # This runs for each tag that is created and adds the corresponding files.
    - provider: releases
      api_key: "$GH_TOKEN"
      file: 
        - main.py

      skip_cleanup: true
      on:
          all_branches: true
          tags: true